apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: sub-engine-network-policy
  namespace: sub-engine
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: sub-engine
      ports:
        - protocol: TCP
          port: 8080
        - protocol: TCP
          port: 8081
        - protocol: TCP
          port: 8082
        - protocol: TCP
          port: 8083
        - protocol: TCP
          port: 8084
        - protocol: TCP
          port: 8761
        - protocol: TCP
          port: 9090
        - protocol: TCP
          port: 3000
        - protocol: TCP
          port: 5432
        - protocol: TCP
          port: 27017
        - protocol: TCP
          port: 9092
        - protocol: TCP
          port: 6379
        - protocol: TCP
          port: 9187
        - protocol: TCP
          port: 9188
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: sub-engine
      ports:
        - protocol: TCP
          port: 8080
        - protocol: TCP
          port: 8081
        - protocol: TCP
          port: 8082
        - protocol: TCP
          port: 8083
        - protocol: TCP
          port: 8084
        - protocol: TCP
          port: 8761
        - protocol: TCP
          port: 9090
        - protocol: TCP
          port: 3000
        - protocol: TCP
          port: 5432
        - protocol: TCP
          port: 27017
        - protocol: TCP
          port: 9092
        - protocol: TCP
          port: 6379
        - protocol: TCP
          port: 9187
        - protocol: TCP
          port: 9188