apiVersion: v1
kind: Service
metadata:
  name: billing-postgres
  namespace: sub-engine
  labels:
    app: billing-postgres
spec:
  selector:
    app: billing-postgres
  ports:
    - port: 5432
      targetPort: 5432
      name: postgres
  clusterIP: None