apiVersion: v1
kind: Service
metadata:
  name: subscription-postgres-exporter
  namespace: sub-engine
  labels:
    app: subscription-postgres-exporter
spec:
  selector:
    app: subscription-postgres-exporter
  ports:
    - port: 9187
      targetPort: 9187
      name: metrics
  type: ClusterIP