apiVersion: v1
kind: Service
metadata:
  name: billing-service
  namespace: sub-engine
  labels:
    app: billing-service
spec:
  selector:
    app: billing-service
  ports:
    - port: 8082
      targetPort: 8082
      name: http
  type: ClusterIP