apiVersion: v1
kind: Service
metadata:
  name: subscription-service
  namespace: sub-engine
  labels:
    app: subscription-service
spec:
  selector:
    app: subscription-service
  ports:
    - port: 8081
      targetPort: 8081
      name: http
  type: ClusterIP