apiVersion: v1
kind: Service
metadata:
  name: alloy
  namespace: sub-engine
  labels:
    app: alloy
spec:
  selector:
    app: alloy
  ports:
    - port: 9080
      targetPort: 9080
      name: http
    - port: 4317
      targetPort: 4317
      name: otlp-grpc
    - port: 4318
      targetPort: 4318
      name: otlp-http
  type: ClusterIP