apiVersion: v1
kind: Service
metadata:
  name: tempo
  namespace: sub-engine
  labels:
    app: tempo
spec:
  selector:
    app: tempo
  ports:
    - port: 3200
      targetPort: 3200
      name: http
    - port: 9411
      targetPort: 9411
      name: zipkin
  type: ClusterIP